services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: gitblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend

    container_name: backend

    depends_on:
      - postgres

    env_file:
      - ./backend/.env

    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend

    container_name: frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres_data: